instructions = [
    "SET FOREIGN_KEY_CHECKS=0;",
    "DROP TABLE IF EXISTS user;",
    "DROP TABLE IF EXISTS queries;",
    "DROP TABLE IF EXISTS species;",
    "DROP TABLE IF EXISTS chromosomes;",
    "DROP TABLE IF EXISTS genes;",
    "SET FOREIGN_KEY_CHECKS=1;",
    """
           CREATE TABLE user (
            id INT PRIMARY KEY AUTO_INCREMENT,
            username VARCHAR(50) UNIQUE NOT NULL,
            password VARCHAR(1000) NOT NULL
        )
    """,
    """
        CREATE TABLE queries (
            id INT PRIMARY KEY AUTO_INCREMENT,
            created_by INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            id_specie INT,
            id_chromosome INT,
            id_genes INT,
            name_gen VARCHAR(255),
            FOREIGN KEY (created_by) REFERENCES user (id)
        )
    """,
    """
        CREATE TABLE species (
            id_specie INT PRIMARY KEY AUTO_INCREMENT,
            specie VARCHAR(255) UNIQUE NOT NULL
        )
    """,
    """
        CREATE TABLE chromosomes(
            id_chromosome INT PRIMARY KEY AUTO_INCREMENT,
            id_specie INT NOT NULL,
            gbig VARCHAR(255),
            number INT(11) NOT NULL,    
            description VARCHAR(255),
            sequence TEXT NOT NULL,
            size INT(11),
            FOREIGN KEY fk_id_specie(id_specie) REFERENCES species(id_specie)
        )
    """,
    """
        CREATE TABLE genes (
            id_genes INT PRIMARY KEY AUTO_INCREMENT,
            id_chromosome INT(11) NOT NULL,
            start INT(11) NOT NULL,
            end INT(11) NOT NULL,
            strand VARCHAR(255),
            size INT(11),
            name_gen VARCHAR(255),
            FOREIGN KEY fk_id_chromosome(id_chromosome) REFERENCES chromosomes(id_chromosome)
        );
    """,
    "INSERT INTO species (specie) VALUES ('homo_sapiens');",
    "INSERT INTO chromosomes (id_specie,gbig,number,description,sequence,size) VALUES (1,'none',1,'GRCh38.p13 Primary Assembly NC_000001.11 1 248956422', 'GTGAAAGGAGGCGGGCCCGCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCTCGCT',1);",
    "INSERT INTO chromosomes (id_specie,gbig,number,description,sequence,size) VALUES (1,'none',2,'GRCh38.p13 Primary Assembly NC_000002.12 1 242193529','CCTGAACTCAGGCTAGGGGTGGGGGAGGGGGTGGTGGGGGTGGGGAAGGGGGTGGGGGGTGAGCCAGGGGAGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGGTGTGGTGGTGGTGGTGGT',1);",
    "INSERT INTO chromosomes (id_specie,gbig,number,description,sequence,size) VALUES (1,'none',3,'GRCh38.p13 Primary Assembly NC_000003.12 1 198295559','AGCCCTCCCCAGGCTGGGGCTGAGCCCTGGGAGGCTCAGGGGAGGGCTGGGGCTGAGCCTGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGGCTGGGGCTGAGCCCGGGAGG',1);",
    "INSERT INTO user (username,password) VALUES ('not_user','not_password');",
]
